### ISSUE TITLE
build-toolchain fails to compile with clang on Mac OS X due to bracket depth

### ISSUE THREAD

**Issue by tplover** [vitasdk/buildscripts#12]
Compiling with the build-toolchain.sh script on Mac OS X (10.7 and above) using Clang will produce an error, where the bracket depth is beyond 256.  The issue occurs around the "echo Task [III-1] /$HOST_NATIVE/gcc-first" section of the build-toolchain.sh script.

It seems like this is a common issue with Clang since by default, the bracket depth is set to 256 but there is a flag that can be used to change the depth size: -fbracket-depth.  However, there does not seem to be a way to set it for the CPPFLAGS in the build-toolchain.sh script to stop the compilation from failing.

Note:  The issue does not occur when using GCC to compile with the build-toolchain.sh script since it produces the correct output in the install-native folder.

**Comment by xyzz** [comment]
Note that gcc doesn't have the flag `-fbracket-depth` so this should be set conditionally only when the compiler is clang, otherwise the compile will fail.

**Comment by joshdekock** [comment]
This has also been fixed
