### ISSUE TITLE
GCC 6 support

### ISSUE THREAD

**Issue by soarqin** [vitasdk/buildscripts#20]
The macro patch is not compatible with the one in GCC 4/5 series,
I have made a new patch for GCC 6 here:
https://github.com/soarqin/vitasdk-msys2/blob/gcc6/patch/gcc.patch
This is tested to be working fine.

**Comment by gordon0001** [comment]
i used your repo for building gcc-6.2.0, just modified it to make it compile on mac osx, also i use the newly bugfixed version of binutils, now making .velfs with c++ works. no relocation errors anymore. before i didnt use the new version and had relocation errors, and i had to include this fix too https://github.com/vitasdk/vita-toolchain/pull/49

**Comment by soarqin** [comment]
@gordon0001 As recent discussions in vitasdk/vita-toolchain:#52 commits from 173210 are reverted in mainline, just use the old code to get everything working fine

**Comment by gordon0001** [comment]
well, so far his code is working fine after a little change of code. everything is set up now with his code and aslong i dont encounter any other issues i wont change anything working

**Comment by soarqin** [comment]
@gordon0001 btw, I have reused vitasdk-mingw scripts and created a new project here: https://github.com/soarqin/vitasdk-build
It supports not only msys2/mingw but also linux/BSD/macOS.
I have only tested it on Linux, so any bug report or PR is welcome if you are willing to test it.

**Comment by joshdekock** [comment]
GCC 6.2.0 is now the default.
