### ISSUE TITLE
binutils bug 20595

### ISSUE THREAD

**Issue by 173210** [vitasdk/buildscripts#21]
binutils bug 20595 make builds corrupted and now vita-create-elf rejects to process the malformed executable (https://github.com/vitasdk/vita-toolchain/commit/37ff30b92122313c39bd428266f99bec9a53c5dc).
https://sourceware.org/bugzilla/show_bug.cgi?id=20595

As you can see in Bugzilla, a patch to fix the bug is now available, but it is for the latest version and will need much efforts to backport the patch because some necessary changes such as commit 491d01d3da18fb61fa6c7c61c091b4cb8c5773f7 are missing.
https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;h=491d01d3da18fb61fa6c7c61c091b4cb8c5773f7

Should we update binutils? In the case we should update `README.md` to note that.

**Comment by 173210** [comment]
A new patch has been sent to the mailing list. We may have to wait it gets merged.
https://sourceware.org/ml/binutils/2016-09/msg00204.html

**Comment by 173210** [comment]
The new patch is merged. Are they really reviewing the patch, by the way? It looks like merged immidately.
https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;h=9eaff8613893f063400fdae95bc382ab33685e3b

**Comment by 173210** [comment]
Updates in the status I posted on Twitter:
* Binutils should be 2.7+ or you need to backport some patches.
* Binutils 2.7+ is not compatible even with GCC 5.4 of 2016q3.
* Binutils of the ARM Embedded Version doesn't have backported patches (so it's a sh*t IMO)

In conclusion, update GCC to 6.x or backport changes.

**Comment by soarqin** [comment]
check my build scripts soarqin/vitasdk-build
using gcc 6.2.0 and binutils 2.27
I have added patches as @173210 said, either this patch and the one for binary compilation.

**Comment by joshdekock** [comment]
Fixed with cmake merge
