### ISSUE TITLE
Building with clang fails

### ISSUE THREAD

**Issue by yifanlu** [vitasdk/buildscripts#3]
This applies to OSX but I think with clang in general:
http://stackoverflow.com/questions/17417978/compiling-gmp-library-on-osx-10-9-with-c-enabled

The simple solution is to modify `build-native/host-libs/usr/include/gmp.h` with the changes from the link above. There should be a better fix, but I don't know what we can do with just the build scripts.

**Comment by joshdekock** [comment]
Building on clang and OSX all works now
