### ISSUE TITLE
Bintrail not updated anymore

### ISSUE THREAD

**Issue by yne** [vitasdk/buildscripts#30]
Last update seems to be from 10-19
```
for status in $(curl -sL https://goo.gl/QpX5zM  | grep -o '>.*gcc-4.9.*txt') ; do curl -sL "https://bintray.com/vitasdk/vitasdk/download_file?file_path=${status:1}" | grep 'Built at'; done;
```
Also, the directory system is not very usable.
Would it be possible to have the build date in the file name, before the buildID ?
Users could easily retrieve build from yesterday without having to list every build.txt

**Comment by DaveeFTW** [comment]
10-19 is the last working version of the toolchain. Hopefully will have it updated and working later today. I will take your suggestion onboard.

**Comment by yne** [comment]
Any way to keep in touch with the SDK build status (beside having to cron a curl on bintray.com) ?
Because usually, issues are closed only once resolved.

I can't wait to test all those taiHEN features. ;-)
