### ISSUE TITLE
Windows builds are missing libwinpthread-1.dll

### ISSUE THREAD

**Issue by xyzz** [vitasdk/buildscripts#36]
As a result, they don't work at all.

```
---------------------------
arm-vita-eabi-gcc-6.2.0.exe - System Error
---------------------------
The program can't start because libwinpthread-1.dll is missing from your computer. Try reinstalling the program to fix this problem. 
---------------------------
OK   
---------------------------
```

Worked around on msys2 by using mingw64 and installing the `mingw64/mingw-w64-x86_64-libwinpthread-git` package.

**Comment by devnoname120** [comment]
@codestation How can we statically link these libraries for the Windows build?

**Comment by codestation** [comment]
libwinpthread-1.dll isn't linked when built using Ubuntu Xenial (16.04 LTS). It is possible switch to the xenial image on travis?

**Comment by devnoname120** [comment]
Unfortunately, [Travis doesn't support Ubuntu Xenial](https://github.com/travis-ci/travis-ci/issues/5821). We could use a Docker container but in addition to the increased complexity for maintenance, our builds are already often timing out so it would be even worse with Docker.

I wonder if there is another way to avoid this dependency.

**Comment by devnoname120** [comment]
@codestation Note that since then Travis-CI has increased the maximum running time of `vitasdk/autobuilds` to 90 minutes. Building in a Ubuntu Xenial container should not time out.

**Comment by devnoname120** [comment]
Note that Travis-CI now supports Ubuntu Xenial. Statically linking pthread and removing the DLLs would fix issues such as https://github.com/vitasdk/buildscripts/issues/63.
