### ISSUE TITLE
Freebsd compilation fails

### ISSUE THREAD

**Issue by devingDev** [vitasdk/buildscripts#40]
I can not compile on freebsd. I followed the same steps as for Linux except that build-essential can not be installed but it apparently is part of the system already.

Any idea what to do? I end up with Error code 2.

**Comment by devingDev** [comment]
[ 70%] Building C object src/CMakeFiles/vita-elf-create.dir/elf-create-argp.c.o
[ 73%] Building C object src/CMakeFiles/vita-elf-create.dir/vita-elf.c.o
/userdev/vita/vitasdkcompile/buildscripts/build/vita-toolchain_build-prefix/src/vita-toolchain_build/src/vita-elf.c:505:91: error:
      use of undeclared identifier 'MAP_NORESERVE'
  ...PROT_NONE, MAP_PRIVATE | MAP_ANONYMOUS | MAP_NORESER...                                              ^
1 error generated.
gmake[5]: *** [src/CMakeFiles/vita-elf-create.dir/build.make:111: src/CMakeFiles/vita-elf-create.dir/vita-elf.c.o] Error 1
gmake[4]: *** [CMakeFiles/Makefile2:292: src/CMakeFiles/vita-elf-create.dir/all] Error 2
gmake[3]: *** [Makefile:128: all] Error 2
gmake[2]: *** [CMakeFiles/vita-toolchain_build.dir/build.make:113: vita-toolchain_build-prefix/src/vita-toolchain_build-stamp/vita-toolchain_build-build] Error 2
gmake[1]: *** [CMakeFiles/Makefile2:343: CMakeFiles/vita-toolchain_build.dir/all] Error 2
gmake: *** [Makefile:84: all] Error 2

**Comment by devingDev** [comment]
Above I tried gmake because i
I thought that would work but it did not.

**Comment by devingDev** [comment]
Also if I do not edit CMakeLists.txt and set the host and build to amd64 it wont work because otherwise it sets them to amd64-- and this error comes up when doing cmake ..

userdev/vita/vitasdkcompile/buildscripts/build # cmake ..
-- The C compiler identification is Clang 3.8.0
-- The CXX compiler identification is Clang 3.8.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/CC
-- Check for working CXX compiler: /usr/bin/CC -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /usr/local/bin/git (found version "2.9.2")
FATALUnsupported system: FreeBSD
FATALUnsupported system: FreeBSD
-- Host:   amd64--
-- Build:  amd64--
-- Target: arm-vita-eabi
-- Configuring done
-- Generating done
-- Build files have been written to: /userdev/vita/vitasdkcompile/buildscripts/build

**Comment by devnoname120** [comment]
`MAP_NORESERVE` is not supported by FreeBSD, try adding this code somewhere:

```C
#ifndef MAP_NORESERVE
#define MAP_NORESERVE 0
#endif
```

**Comment by devingDev** [comment]
I will try this later. The reason I wanted to compile is I could not use the one SDK which gets instaled on vitasdk.org
I got an error when compilig Vita Projects that GLIBC_2.14 was not found.
I was then hinted by an freebsd irc user to uninstall the port linux_base-c6 and instead install the port linux_base-c7 . Both of them emulate the linux environment ( if set up right 64 bit ).
Not I could compile it fine BUT I had to use gmake. make fails.

**Comment by devingDev** [comment]
What I meant is : Now I could compile the projects with c7 installed.

**Comment by endrift** [comment]
This was fixed by https://github.com/vitasdk/vita-toolchain/commit/25d343b448d4d4f9883b6f38e44a4e0ac8355865 and #44, although you still have to move libelf.h out of the way in /usr/include before you try to build, or else you'll wind up with a broken vita-elf-create.
