### ISSUE TITLE
Fails to patch GCC

### ISSUE THREAD

**Issue by IngwiePhoenix** [vitasdk/buildscripts#54]
This:

```
[ 67%] Performing configure step for 'gcc-base'
/bin/sh: -fbracket-depth=512: command not found
make[2]: *** [gcc-base-prefix/src/gcc-base-stamp/gcc-base-configure] Error 127
make[1]: *** [CMakeFiles/gcc-base.dir/all] Error 2
make: *** [all] Error 2
```

should explain everything. :) Since there was no download for a pre-built toolchain, I decided to try and build my own. Well, here I am, not able to do so. Any idea how I can work around this?

**Comment by IngwiePhoenix** [comment]
I found out what exactly breaks: https://github.com/vitasdk/buildscripts/blob/master/CMakeLists.txt#L478

You need to surround this with quotes, obviously. :) ` CFLAGS=-DNO_IMPLICIT_EXTERN_C -fbracket-depth=512` needs to have quotes, otherwise the shell will interpret the `-fbracket-depth` switch as a command. I will manually fix this locally and if wanted, make a PR off it.

**Comment by IngwiePhoenix** [comment]
Removing the addition of the `-fbracket-depth=512` option solved this issue. Still, you do need quotation...

**Comment by rsn8887** [comment]
Could you make a PR if you found a fix?

**Comment by IngwiePhoenix** [comment]
Just remove the `-fbracket-depth=512` fix... That's all that I did. I don't know if making a PR for such a minimal change is really a good idea? :)
