### ISSUE TITLE
How to build a Docker image equivalent to vitasdk/vitasdk?

### ISSUE THREAD

**Issue by Jmgr** [vitasdk/buildscripts#92]
I have found what I think is a bug in `newlib` and have created a [PR](https://github.com/vitasdk/newlib/pull/51) for it.

I would like to create a temporary Docker image while it is under review, like `vitasdk/vitasdk` on Docker Hub. Using this `buildscripts` repository I have managed to create an image, see `jmgrcpp/vitasdk`, but it does not contain many libraries included in `vitasdk/vitasdk` like SDL2.

Where can I find the Dockerfile for `vitasdk/vitasdk`, since it seems to be the official Docker image for the vitasdk?

**Comment by Jmgr** [comment]
@frangarcj you seem to be the person who has pushed the vitasdk/vitasdk Docker image on Docker Hub, right? Do you know where I could find the Dockerfile that has been used to create it?

**Comment by frangarcj** [comment]
https://github.com/vitasdk/docker

**Comment by Jmgr** [comment]
Awesome, thanks.
